services:
  db:
    ports:
      - "1433:1433"
    build:
      context: db-init
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - db:/var/opt/mssql
  server:
    depends_on:
      - db
    ports:
      - "8080:8080"
    build:
      context: Eletro-BOB_API
  generate-mobile-app:
    build:
      context: electro-bob
      dockerfile: create_apk.dockerfile
    volumes:
      - client:/var/client/
    image: internal/web
  web:
    depends_on:
      - generate-mobile-app
      - server
    build:
      context: electro-bob
      dockerfile: web-client.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - client:/var/client/
    environment:
      - API_URL=${API_URL}

volumes:
  client:
  db:
