services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=AreaDB
    volumes:
      - db:/var/opt/mssql
      - /backup-volume:/backup
  server:
    depends_on:
      - db
    ports:
      - "8080:8080"
    build:
      context: Eletro-BOB_API
  generate-mobile-app:
    build:
      context: electro-bob
      dockerfile: create_apk.dockerfile
    volumes:
      - client:/var/client/
    image: internal/web
  web:
    depends_on:
      - generate-mobile-app
    build:
      context: electro-bob
      dockerfile: web-client.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - client:/var/client/
    environment:
      - API_URL=${API_URL}
      - AUTH_ORIGIN=/electro-bob

volumes:
  client:
  db:
