services:
  generate-mobile-app:
    build:
      context: electro-bob
      dockerfile: create_apk.dockerfile
    volumes:
      - client:/var/client/
    image: internal/web
  web:
    depends_on:
      - generate-mobile-app
    build:
      context: electro-bob
      dockerfile: web-client.dockerfile
    ports:
      - "8001:3000"
    volumes:
      - client:/var/client/

volumes:
  client:
