services:
  web:
    depends_on:
      - generate-mobile-app
    build:
      context: electro-bob
      dockerfile: web-client.dockerfile
    ports:
      - "3000:8001"
    volumes:
      - ./mobile-app:/var/mobile-app
  generate-mobile-app:
    build:
      context: electro-bob
      dockerfile: create_apk.dockerfile
    volumes:
      - ./mobile-app:/var/mobile-app
